apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-first-app
  template:
    metadata:
      labels:
        app: my-first-app
    spec:
      containers:
      - name: k8s-demo
        image: vuduchailinh/my-first-app
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: nodejs-port
          containerPort: 3000
        volumeMounts:
          - mountPath: /etc/creds
            name: cred-volume
            readOnly: true
      volumes:
        - name: cred-volume
          secret:
            secretName: db-secrets
