apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    name: database
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3306
        name: mysql-port
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            key: rootPassword
            name: myFirstApp-secrets
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            key: username
            name: myFirstApp-secrets
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: myFirstApp-secrets
      - name: MYSQL_DATABASE
        valueFrom:
          secretKeyRef:
            key: database
            name: myFirstApp-secrets
