apiVersion: 1
kind: ReplicationController
metadata:
  name: my-first-app-controller
spec:
  replicas: 2
  selector:
    app: my-first-app
  template:
    metadata:
      labels:
        app: my-first-app
    spec:
      containers:
        - name: k8s-demo
          image: vuduchailinh/my-first-app
          ports:
            - containerPort: 3000
