apiVersion: v1
kind: Service
metadata:
  name: my-first-app-service
spec:
  selector:
    app: my-first-app
  ports:
  - port: 31001
    nodePort: 3100
    targetPort: nodejs-port
    protocol: TCP
  type: NodePort
